version: "3.7"

services:
  database_lysei:
    image: postgres
    container_name: database_lysei
    restart: always
    ports:
      - 35432:5432
    environment:
      - POSTGRES_USER=lysei
      - POSTGRES_PASSWORD=hackaton
      - POSTGRES_DB=lysei
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: lysei
  #   ports: 
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database_lysei
  #   depends_on:
  #     - database_lysei



volumes:
  pgdata:
    driver: local